config/routes.rb
Rails.application.routes.draw do
  

  

  resources :auctions do 
    resources :bids
  end

  root "auctions#index"

end

app/models/auction.rb
class Auction < ActiveRecord::Base
has_many :bids
validates :title, presence: true
def check_highest_bid
    highest_bid = self.bids.order("amount DESC").first.amount rescue 0
    self.reserve_price = highest_bid
    save
  end


end

app/models/bid.rb
class Bid < ActiveRecord::Base
belongs_to :auction

validates :amount, presence: true
scope :ordered_by_creation, -> { order("created_at DESC") }
#validates_numericality_of :amount, :greater_than => Bid.last.amount
validate :check_if_highest_bid

  after_save :update_auction
  after_destroy :update_auction

  def update_auction
    self.auction.check_highest_bid
  end     

  def check_if_highest_bid
     errors.add(:amount, "must be higher than current bid") unless self.auction.reserve_price < self.amount
  end
end



#validate :bid_is_higher_than_current_highest
#private 

#def bid_is_higher_That_current_highest
#  bid > auction.current_highest_bid
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
before_action :find_auction, only: [:edit, :show, :update, :destroy]



def index
  @auctions = Auction.all 
  
end

def new 
  @auction = Auction.new
  
end

def create
  @auction = Auction.new(auction_params)
  if @auction.save
    redirect_to @auction, notice: "Auction created."
  else
  render :new
  end
end  

def edit 
  
end

def show 
  @bid = Bid.new
  @bids = @auction.bids
  
end

def update
  if @auction.update_attributes(auction_params)
    redirect_to @auction, notice: "Auction updated"
  else
    render :edit
  end
end

def destroy
  @auction.destroy
  redirect_to auctions_path, notice: "Auction deleted"
end




private

def auction_params
  params.require(:auction).permit(:title, :details, :end_time, :reserve_price, :price)
end

def find_auction
  @auction = Auction.find(params[:id])
end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :find_auction
  

  def create
    @bid = @auction.bids.new(bid_params)
    if@bid.save
      redirect_to @bid.auction
    else

      redirect_to @bid.auction, notice: "You didn't bid high enough"
  
    end
  end

  


  

  private


    
   

    def bid_params
      params.require(:bid).permit(:amount)
    end

    def find_auction
      @auction = Auction.find params[:auction_id]
    end

    def find_bid
      @bid = Bid.find params[:id]
    end  
   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/auctions/_auction.html.haml
%h2= link_to auction.title, auction
%p.auction-display=auction.details
%p.auction-display=auction.reserve_price
%hr

app/views/auctions/_form.html.haml
.col-md-8.col-lg-8
  = simple_form_for @auction, html: {class: "form-horizontal"} do |f|
    = f.input :title
    = f.input :details
    = f.input :end_time
    = f.input :price
    = f.submit "Save", class: "btn btn-primary"

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render "form", button_label: "update it." %>

app/views/auctions/index.html.haml
.col-md-8.col-lg-8
  %h1 Welcome to Auction House 

  = link_to "New Auction", new_auction_path, class: "btn btn-primary", id: "new-auction"
  = render @auctions

app/views/auctions/new.html.haml
%h1 Create New Auction

= render "form"

app/views/auctions/show.html.haml
.col-md-8
  = link_to "Home", root_path, class: "btn btn-primary"
  %h1=@auction.title
  %p=@auction.details
  %p=@auction.end_time.strftime("%B, %d, %Y")
  %p=@auction.price

  = link_to "Edit", edit_auction_path(@auction), class: "btn btn-info"
  |
  = link_to "Delete", @auction, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"
  %hr

  #bids-create
    = simple_form_for [@auction, Bid.new] do |f|
      =f.input :amount, label: "Amount:"
      %br
      =f.submit "Bid", class: "btn btn-primary"
  %hr    

  .row
    .col-md-8.col-lg-8
      .well
        %h3= "Current Price:" 
        %p=@auction.reserve_price
    %h2 Bids: 
    .col-md-8.col-lg-8
      .well
        -@bids.each do |bid| 
          .well-bids
            = "$"
            =bid.amount
            %hr
            =bid.created_at.strftime("%B, %d, %Y")
            %br

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AuctionHouse
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - elsif flash[:alert]
        .alert.alert-danger= flash[:alert]
    = yield